volumes:
  ourspace:
    external: true
  # pg-admin:
  #   external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh # runs run.sh file, change script in package.json
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_JOBS_HOST: http://localhost:8080
  jobs:
    build:
      context: ./jobs/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./jobs/api:/app
    environment:
      DATABASE_URL: postgresql://ourspace:ourspace@db/ourspace
      ADZUNA_API_KEY: ${ADZUNA_API_KEY}
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578

  db:
    image: postgres:14.2-bullseye
    volumes:
      #for your initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      # For the data stored by PostgreSQL
      - ourspace:/var/lib/postgresql/data
    environment:
      #for the superuser of postgres instance- must be same as above
      # Password for the postgres superuser
      # See 01-create-databases.sql for the name/password
      #   for the user of the application database
      POSTGRES_PASSWORD: ourspace
    ports:
      - "15432:5432"
