volumes:
  ourspace:
    external: true
  pg-admin:
    external: true
services:
  jobs:
    build:
      context: ./jobs/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./jobs/api:/app
    environment:
      DATABASE_URL: postgresql://ourspace:ourspace@db/jobs
      ADZUNA_API_KEY: ${ADZUNA_API_KEY}
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578