# This is the YAML file for Render
# It will deploy our Dockerized FastAPI backend and React frontend
database:
  name: ourspace
  databaseName: ourspace
  user: ourspace

services:
  # Declare the name of the service
  type: web
  name: our-space
  env: docker
  region: ohio
  plan: free

  
  envVars:
    DATABASE_URL: ${{ env.DATABASE_URL }}
  dockerfilePath: ./jobs/api/Dockerfile # optional
  dockerContext: ./jobs/api # optional
  


secrets:
  - name: my-dotenv
    type: dotenv
    path: .env