databases:
  - name: ourspace
    databaseName: ourspace
    user: ourspace
    
services:
  - type: web
    name: our-space
    env: docker
    region: ohio
    plan: free
    repo: https://github.com/rkschlos/our_space.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ourspace
          property: connectionString

  dockerfilePath: ./jobs/api/Dockerfile 
  dockerContext: ./jobs/api
  
  - type: pserv
    name: pgbouncer
    env: docker
    plan: free
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
    - key: DATABASE_URL
      fromDatabase:
      name: ourspace
      property: connectionString
    - key: POOL_MODE
      value: transaction
    - key: SERVER_RESET_QUERY
      value: DISCARD ALL
    - key: MAX_CLIENT_CONN
      value: 10
    - key: DEFAULT_POOL_SIZE
      value: 5


secrets:
  - name: my-dotenv
    type: dotenv
    path: .env