databases:
- name: ourspace
  databaseName: ourspace
  user: ourspace

services:
- type: web
  name: our-space
  env: docker
  region: ohio
  plan: free
  repo: https://github.com/rkschlos/our_space.git
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: ourspace
      property: connectionString

  dockerfilePath: ./jobs/api/Dockerfile 
  dockerContext: ./jobs/api
  
 

