FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app

# Copy the top-level files
COPY __init__.py __init__.py
COPY jobs_db.py jobs_db.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
CMD python jobs_db.py
